[General]
#shapefile = "/data/s1_oman/roi/oman_roi.shp"
mindate = 2021-01-01T00:00:00Z
maxdate = 2021-12-31T23:59:00Z

[Download]
### Download files
download = false
download_dir = "/data/s1_oman/slc/2021/"
username = "stevenmhill"
password = "earthdataMuffIN88"
platform = "Sentinel-1A"
processinglevel = "SLC"
beammode = "IW"
polarization = "VV+VH"
processes = 40

[Processing]
data = "/data/s1_oman/slc"

### Products
int_proc = false
coh_proc = true
ha_proc = false
slice_assembly = true
#subset = True
pol = "full"
t_crs = 32640
outdir_int =  "/data/s1_oman/intensity/"
outdir_coh = "/data/s1_oman/coherence/consecutive/"
outdir_ha = "/datacube/indexed_data/eocube/sentinel1/ha/2019/"
tmpdir = "/data/s1_oman/tempdirCON"
res_int = 20 
res_coh = 20 
res_ha = 20 
out_format = "GeoTIFF"
#gpt_paras = None
iws = ["IW1","IW2","IW3"] 
ext_dem = false 
ext_dem_nodatval = -9999 
#ext_dem_file = None 
msk_nodatval = false 
ext_dem_egm = true
decompfeats = ["Alpha", "Entropy", "Anisotropy"]
#ha_speckFilter= "Box Car Filter"
decomp_win_size= 5 
#osvpath= None
imgresamp= "BICUBIC_INTERPOLATION" 
demresamp= "BILINEAR_INTERPOLATION" 
bgc_demresamp= "BICUBIC_INTERPOLATION" 
tc_demresamp= "BILINEAR_INTERPOLATION"
cohwinrg= 11 
cohwinaz= 3 
speckfilter= "Boxcar" 
filtersizex= 5 
filtersizey= 5 
ml_rglook= 4 
ml_azlook= 1
l2db_arg= true 
ref_plain= "gamma"
clean_tmpdir= true
osvfail= false
tmp_format = "BEAM-DIMAP"
